//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<questions>();
            }
        }
    }
    public partial class questions
    {
        [PrimaryKey, AutoIncrement]
        public Int64 question_id { get; set; }
        
        [MaxLength(300)]
        [NotNull]
        public String question { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String answer { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String other_question { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String other_question2 { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String other_question3 { get; set; }
        
        [MaxLength(15)]
        [NotNull]
        public String subject { get; set; }
        
    }
    
}
